### ISSUE TITLE
Side menu Opacity.

### ISSUE THREAD

**Issue by TheEvasion** [TheCommieAxolotl/BetterDiscord-Stuff#1]
This isn't an issue at all, and I never use Github so I really don't know the place to offer a suggestion. So apologies for putting it in here. But I just wanted to suggest the idea of upping the opacity for the side menu and Role menu a bit, since it's kind of hard to scan all of the channels and roles with your eyes when there are a lot to scan. (Takes extra time to do so than normal)

As well as the side menu for roles, it seems a bit hard to read for them as well. Other than that, love the theme, especially the neon indicators to the left, makes it easy to recognize new messages inside the channels.

**Additional context**
![image](https://user-images.githubusercontent.com/81767737/148632014-1fef7237-3589-45b7-add6-fcb2770af176.png) , 
![image](https://user-images.githubusercontent.com/81767737/148632082-8f560d5c-913e-45b8-ac21-822f244eeff8.png)

**Comment by TheCommieAxolotl** [comment]
You can edit the `--channels-default` variable in the theme file for the channel names and things, 
for the memberlist headers put 
```css
.membersGroup-v9BXpm, .membersGroup-2eiWxl {
    opacity: 0.5;
}
```in custom css
