### ISSUE TITLE
[Bug] CleanUpConfigs.plugin.js Broken

### ISSUE THREAD

**Issue by zluckytraveler** [TheCommieAxolotl/BetterDiscord-Stuff#10]
### Addon

CleanUpConfigs.plugin.js

### What happened?

The new discord update broke all plugins. However Better Discord just pushed out a new update for all plugins to start working again. Can we please get this one fixed? Thanks!

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
CleanUpConfigs is now deprecated [68e6254](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/68e625490cf59fa91e74a491639ff4229397bbb6)
