### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by omaryomario** [TheCommieAxolotl/BetterDiscord-Stuff#102]
### Addon

Timezone

### What happened?

i cant use the script on vencord atalll, i tried converting it by some users help to ts or tsx so i could use it on vencord and it doesnt want to work atall :(

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
this is not a vencord addon

**Comment by omaryomario** [comment]
oh mannnnn
