### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Aghneel** [TheCommieAxolotl/BetterDiscord-Stuff#12]
### Addon

BetterSyntax.plugin.js

### What happened?

Plugin crashes when switch channel.

### What Discord version do you have this issue on?

Stable

### Logs

```shell
http://0x0.st/oxU4.png
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Duplicate of #11

**Comment by TheCommieAxolotl** [comment]
Sorry, that's my mistake. I forgot to do a version bump so the update wasn't shown to many people, i've just done that now.
