### ISSUE TITLE
[Bug] JS code wrong version #

### ISSUE THREAD

**Issue by Nova1ite** [TheCommieAxolotl/BetterDiscord-Stuff#13]
### Addon

BetterSyntax

### What happened?

Wrong version number in JS code
![Untitled](https://user-images.githubusercontent.com/115776661/197653286-81b3db48-b2ee-4109-a03f-9c88af754ad1.png)

### What Discord version do you have this issue on?

Canary

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
[c524bcb](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/c524bcb4e87d10874c280a3a59be44054c2f121a)
