### ISSUE TITLE
[Bug] BetterSyntax - utility buttons not appearing

### ISSUE THREAD

**Issue by shamshitty** [TheCommieAxolotl/BetterDiscord-Stuff#16]
### Addon

BetterSyntax

### What happened?

The utility buttons that usually appear at the bottom of codeblocks do not appear. ive turned off my themes and other plugins and nothing changes

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Fixed in [cf6f986](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/cf6f9860f28526389be6b20c1930d8e8748f002d)
