### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by EconomicSacks** [TheCommieAxolotl/BetterDiscord-Stuff#17]
### Addon

MaterialDesign

### What happened?

Scrolling on the DMs list using the scroll will cause the DMs list to freeze up

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Known issue, it's because of discord's lazy loading.
I don't think there is anything i can do from the css
