### ISSUE TITLE
BetterSyntax compatibility with BetterCodeblocks

### ISSUE THREAD

**Issue by BigFlubba** [TheCommieAxolotl/BetterDiscord-Stuff#2]
I was wondering if those plugins can both be compatible with one another. Currently, my biggest issue is with copying the code it also copies everything else that BetterCodeblocks has (line numbers and the code language) and messes up the formatting. I was wanting that to be not the issue if possible.

![image](https://user-images.githubusercontent.com/69104450/161860074-7bd55323-c99b-4e4f-8360-e650e9de104a.png)
Copied text (without editing):
`CSS1[alt="Wumpus holding a country-specific flag"] {2display: none;3}`
https://github.com/xiBread/bd-contributions/blob/master/BetterCodeblocks/BetterCodeblocks.plugin.js

**Comment by TheCommieAxolotl** [comment]
Sorry for the late response, I have been on holiday for the past week and am now getting back to things!

Simply put, this won't be worked on. An upcoming update will most likely make the two plugins conflict horribly and I'm unfortunately not going to change that. Thanks for taking the time to make this issue!

**Comment by TheCommieAxolotl** [comment]
Actually, I'm going to take back everything i said in that comment.

I have just tried my development copy of the plugin and they function pretty much in tandem, the issue that you have described is solved and I'm going to keep this issue open and I'll alert you when this update is pushed.

**Comment by TheCommieAxolotl** [comment]
Fixed in  `65e13a9` (`v2.0.0`)
