### ISSUE TITLE
[Suggestion] [Timezones] Add support for timezones by name

### ISSUE THREAD

**Issue by WeirdAlex03** [TheCommieAxolotl/BetterDiscord-Stuff#20]
I really like the idea of this plugin, but I have a significant concern about how the data is entered:

Entering the user's UTC offset is nice and easy for calculations, but it's going to be a HUGE pain come daylight savings. The time zones for each user will have to be manually adjusted. Complicating matters, different regions change at different times, Australia goes forward as the northern hemisphere goes backward, and the specific areas that do and don't are rather complicated. I imagine most users do NOT want to deal with this, and it will not be possible for the plugin to calculate changes just by offset.

Instead, I suggest using a library implementing [tz database](https://en.wikipedia.org/wiki/Tz_database) (or some equivalent), where we can enter the user's timezone name (i.e. `America/New_York` or `Europe/London`). Then, the changes for daylight savings (or anything else) can be automatically handled without any additional effort.

**Comment by Razzaline** [comment]
I second this. This plugin for Shelter (https://github.com/yellowsink/shelter-plugins/blob/master/plugins/timezones/) does exactly that, and adjusts times for daylight saving time. (And before they updated it to have a world map-based timezone picker, you could either enter an offset or a timezone by name.)

**Comment by TheCommieAxolotl** [comment]
I do plan to implement this, however the issue is that currently the workflow for all my BD plugins does not include dependency bundling of any sort. So I would either have to change that or implement something like [timezone](https://npmjs.com/package/timezone) myself.

**Comment by FearNaBoinne** [comment]
#44 would be part of this I think...

**Comment by sophia1000** [comment]
you could get away with just adding the 13 different dst regions as a dropdown or something and keep the current set up. wouldn't be as nice ui wise to add as adding the regions properly but would still give dst functionality in the easiest way and thats all that matters.

**Comment by TheCommieAxolotl** [comment]
This is finally done in the latest version, download it from GitHub.
