### ISSUE TITLE
[Bug] Timezones spacing broken on replies

### ISSUE THREAD

**Issue by maenDisease** [TheCommieAxolotl/BetterDiscord-Stuff#22]
### Addon

Timezones

### What happened?

Replies to users with a timezone set has no spacing
![image](https://user-images.githubusercontent.com/90428263/218345527-6bc228ae-7114-4928-8e8f-4242fe400f5a.png)
Though it might not be intended for the timezone to appear in replies

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TexNat** [comment]
why is it displaying there anyway, shouldn't it be with the timestamp instead of the name?

**Comment by TheCommieAxolotl** [comment]
Fixed in [6c57df3](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/6c57df3b49dee7d4b37fcf97ae637541947ecce0)
