### ISSUE TITLE
[Bug] Timezones duplicate menu item

### ISSUE THREAD

**Issue by maenDisease** [TheCommieAxolotl/BetterDiscord-Stuff#23]
### Addon

Timezones

### What happened?

Re-enabling the plugin causes the Timezones menu item to duplicate
![image](https://user-images.githubusercontent.com/90428263/218345644-d35f047b-74e1-467b-97b4-dcd977af7eb9.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Fixed in [e9fb7e0](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/e9fb7e0291cfe5ad3bc51ec3e52a1a28fe222bf3)
