### ISSUE TITLE
[Bug] Set timezone button doesn't get removed

### ISSUE THREAD

**Issue by Miniontoby** [TheCommieAxolotl/BetterDiscord-Stuff#25]
### Addon

Timezones

### What happened?

When I disable and enable the plugin, there are two "Set timestamp" buttons

This happened when I updated the plugin and when I mannually disabled and enabled it.

If I just disable it, the button stays

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maenDisease** [comment]
Duplicate of #23
