### ISSUE TITLE
[Suggestion] Support for 24h times

### ISSUE THREAD

**Issue by aqsd91** [TheCommieAxolotl/BetterDiscord-Stuff#26]
### Addon

Timezones

### What happened?

So far the plugin only supports 12h cycles, 24h cycles would be greatly appriciated for people living outside of the US/UK countries.

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shamshitty** [comment]
technically it is supported but theres no config button to change it, if you really want the 24 format go to line 256 in the js file and change `hour12` to true

**Comment by aqsd91** [comment]
Thank you, that worked.

**Comment by TheCommieAxolotl** [comment]
What sham said is true but this functionality is planned for the next release so i'm going to reopen this until it's pushed.

**Comment by maxoku** [comment]
> Thank you, that worked.

Did it work? I still have 12h :/

**Comment by TheCommieAxolotl** [comment]
Added in [a370b42](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/a370b428073cf8501b2ea21896fd9f0af188db50)
