### ISSUE TITLE
[Bug] Does not show up

### ISSUE THREAD

**Issue by Auditormadness9** [TheCommieAxolotl/BetterDiscord-Stuff#29]
### Addon

Timezones

### What happened?

The time doesn't show up on their profiles.

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
You must set a user's timezone by right clicking on their name/image and selecting `Set Timezone`.

**Comment by Eden333** [comment]
> You must set a user's timezone by right clicking on their name/image and selecting `Set Timezone`.

It doesn't show up for me in my context menu

**Comment by misterpyrrhuloxia** [comment]
I'm not seeing any timezones as well, not even in the voice channel right-click context menu. Then again, Discord completely crashes each time I try to right-click any user at all in VC list or in my DM list- which has already been reported in #32.
