### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by SirLennox** [TheCommieAxolotl/BetterDiscord-Stuff#3]
### Addon

BetterSyntax

### What happened?

OneDark theme seems buggy (Java)
![image](https://user-images.githubusercontent.com/52826781/172487374-9b9a6f77-c9d9-44a3-9f96-2ae53f1a385d.png)

### What Discord version do you have this issue on?

Latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
As Discord uses an old version of [hljs](https://highlightjs.org/), unfortunately I've had to make some compromises with the colours. 
If you like, you can join my [Support Server](https://discord.gg/5BSWtSM3XU) and send some code examples and I can try to improve the colours 🙃

**Comment by SirLennox** [comment]
ok no problem that isn't your issue but it's just confusing for everyone who uses the plugin.
