### ISSUE TITLE
[Bug] Error when opening Timezones "Set Timezone" menu

### ISSUE THREAD

**Issue by MatthewtheProto** [TheCommieAxolotl/BetterDiscord-Stuff#37]
### Addon

Timezones

### What happened?

whenever i try to  set a  timezone  in discord it says this  *there was an unexpected  error click to open console for more details* i have the latest of  both timezones and zeres s o  idk whats the problem?
![Capture](https://user-images.githubusercontent.com/109949259/226174492-a00fbcaf-6c79-42b6-bd66-20157e5d0303.PNG)

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by foursplaysroblox** [comment]
I laso have this bug

**Comment by EnoralTheOutCast** [comment]
Same. Also having that issue

**Comment by Jugom** [comment]
Can confirm.
It also set timezone to UTC 0 if you click set instead of cancel and now I think I can't revert it either.

**Comment by RuochenFu21** [comment]
> Can confirm. It also set timezone to UTC 0 if you click set instead of cancel and now I think I can't revert it either.

Can confirm this also

**Comment by spectrum705** [comment]
same issue

**Comment by 0xDema** [comment]
Same issue here

**Comment by JJayzX** [comment]
Same

**Comment by PixelGuy123** [comment]
![image](https://user-images.githubusercontent.com/89644121/229290572-47f3024b-4c87-40f7-b0aa-2f488387dc37.png)
It gives this error when trying to open the menu

**Comment by caliburnnnn** [comment]
Yes, still facing this issue.

**Comment by FiraliaDev** [comment]
Same here
