### ISSUE TITLE
[Bug] "Set Timezone" option missing

### ISSUE THREAD

**Issue by FiraliaDev** [TheCommieAxolotl/BetterDiscord-Stuff#41]
### Addon

Timezones

### What happened?

The "Set Timezone" does not show up upon right-clicking a user.

### What Discord version do you have this issue on?

PTB

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Razzaline** [comment]
I'm having this problem on Canary as well. >.<

**Comment by Razzaline** [comment]
Hello! Just wanted to say that updating BetterDiscord from 1.9.1 to 1.9.2 fixed it. ^^
