### ISSUE TITLE
[Bug] PreviewMessage not showing

### ISSUE THREAD

**Issue by Eden333** [TheCommieAxolotl/BetterDiscord-Stuff#51]
### Addon

PreviewMessage

### What happened?

It doesn't show the Icon like in the "Readme" page

for me it looks only like this:

![image](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/assets/18154402/a9807d96-8c4e-4bd0-a039-97c36d3073e8)

and yes, I have the plugin enabled.

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheRedDev** [comment]
Same behavior on linux stable

**Comment by dperlop** [comment]
Same problem

**Comment by TheCommieAxolotl** [comment]
Fixed by ven in #52
