### ISSUE TITLE
[Bug] Ultra Theme

### ISSUE THREAD

**Issue by elBelgg** [TheCommieAxolotl/BetterDiscord-Stuff#64]
### Addon

Ultra theme

### What happened?

If you have this theme enabled, and you click someone badge to see what it is or when they got it... it would not show. The thing is that the badge info is being hiding, because if you click the badge and exit from the profile fast, you will be able to see the badge info

Discord: Enmity

### What Discord version do you have this issue on?

Stable

### Logs

```shell
I have no logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Can you send a video/screenshot of this happening?

**Comment by elBelgg** [comment]
Here it is

https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/assets/85364889/eb35cbaf-ee3b-471b-a9e4-e5b1c3e4ccd2

**Comment by elBelgg** [comment]
I just realized that if you restart Discord it does work, but only with the first profile you look.

**Example:** You just started Discord from scratch, and you go to see your friend's profile, you click on their badges and it works, you leave their profile and come back in, you click on their badges and it doesn't work (it could be any profile, it only works with it first profile THAT YOU SEE THEIR BADGES. It only works in the first profile you click their badges, and only in the first attemp before leaving the profile).

https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/assets/85364889/f38a05d8-3c1c-486e-96dc-5788049f8438
