### ISSUE TITLE
[Bug] The timezone plugin is showing times way in the future

### ISSUE THREAD

**Issue by corysimmons** [TheCommieAxolotl/BetterDiscord-Stuff#65]
### Addon

Timezone

### What happened?

I installed the plugin, set a friend's timezone to `0100` (and `+0100`, and `+100`) and it shows the time as a really distant future.

![image](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/assets/224636/3fb6a23d-2d0f-4bf4-a4a1-4af156a6afc3)

---

I realized as I was posting this that maybe it was just expecting a single int like `1` as the offset instead of the full UTC offset and that fixed it. 😅 Still reporting as the tooltips and such have placeholders like `0100` implying that's the format you should use.

Maybe something like

```js
<label>
  <span>UTC Offset</span>
  <input type="number" min="-12" max="14" step="1" name="utc-offset">
</label>
```

might be better to ensure no one gets confused like I did.

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Closed as this is not an actual bug and the placeholder already reads `-5`.
