### ISSUE TITLE
[Bug] Timezones don't show on user profiles

### ISSUE THREAD

**Issue by QuentinMcCarthy** [TheCommieAxolotl/BetterDiscord-Stuff#74]
### Addon

Timezones

### What happened?

The timezones correctly on messages, but do not display on user profiles like the screenshots imply. As a result there's no way to see the users CURRENT time in their timezone, only the time they sent their messages.

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Are you running the latest version of the plugin from GitHub? I can't replicate this

**Comment by QuentinMcCarthy** [comment]
Latest version from Plugin Repo, which should be the latest version from Github? It could be related to the users in question not having profile banners, perhaps?

**Comment by TheCommieAxolotl** [comment]
This should be fixed, if it isn't reply below and I'll reopen the issue.

**Comment by QuentinMcCarthy** [comment]
Just reinstalled it to check. Set someone's timezone to UTC -5, nothing shows up on their profile as far as I can see.
