### ISSUE TITLE
[Bug] Timezones v1.0.4 crashes Discord every time it's activated

### ISSUE THREAD

**Issue by minnieoo** [TheCommieAxolotl/BetterDiscord-Stuff#76]
### Addon

Timezones v1.0.4 

### What happened?

When I turn Timezones v1.0.4 on, it crashes discord. I only have Timezonesv1.0.4 activated and it only happens when I activate it. 

More info:
Discord - Stable 247082 (7813bfb)
BetterDiscord - Core v1.9.6

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Can't replicate.
