### ISSUE TITLE
[Bug] Insufficient Spacing on Material Design Theme

### ISSUE THREAD

**Issue by DoctorAnon** [TheCommieAxolotl/BetterDiscord-Stuff#8]
### Addon

Material Design Theme

### What happened?

Seen (below), the settings gear is on the literal edge of the user card, making it appear broken and far too much to the right.
![Screenshot 2022-09-22 215642](https://user-images.githubusercontent.com/71120469/191894697-742693b3-c831-41e2-ab7c-f71bdeb607c3.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Fixed in [#6ca23a9](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/commit/6ca23a9ab389cace2514a14bd0930e2095bdb00e)
