### ISSUE TITLE
[Bug] 24-hour clock stopped working after update

### ISSUE THREAD

**Issue by maxoku** [TheCommieAxolotl/BetterDiscord-Stuff#80]
### Addon

Timezones

### What happened?

After update 24-hour clock doesn't work, shows 12-hour clock regardless of the setting.

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Fixed in #84
