### ISSUE TITLE
[Bug] [Timezones] Can't set to UTC -3:30

### ISSUE THREAD

**Issue by Josh-P-B** [TheCommieAxolotl/BetterDiscord-Stuff#82]
### Addon

Timezones

### What happened?

Can not set to UTC -3:30

### What Discord version do you have this issue on?

Stable

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Have you tried entering Newfoundland or variations on it?

**Comment by TheCommieAxolotl** [comment]
<img width="275" alt="Screenshot 2024-01-04 at 11 21 46 am" src="https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/assets/87679354/207e93b2-ab82-410e-a7a0-82c9329b3ed8">
