### ISSUE TITLE
[Feature Request] - Ultra Theme toggle for ChannelName Capitalization

### ISSUE THREAD

**Issue by TheKartel** [TheCommieAxolotl/BetterDiscord-Stuff#83]
Love the Ultra theme it's almost perfect however, there's no current way that I've seen outside of the Raw CSS for the Ultra Theme to toggle or change the "ChannelName" text transform of Capitalization to normal or anything else. Could there be a way to implement a toggle for this or a section in the editable code for this theme within the css ?

**Comment by TheCommieAxolotl** [comment]
Just put this at the bottom of the theme file/custom css

```css
.name__8d1ec {
    text-transform: unset;
}
```

**Comment by TheCommieAxolotl** [comment]
You might need to stick an !important before the `;` @TheKartel
