### ISSUE TITLE
[Bug] Time not displayed on profile without restarting Discord after plugin activation

### ISSUE THREAD

**Issue by Lusiiky** [TheCommieAxolotl/BetterDiscord-Stuff#86]
### Addon

Timezones

### What happened?

If I enable the Timezones plugin, the time of a user with a configured timezone will not be displayed on his profile (profile on the right of the messages or right-click profile) without a restart of Discord, even though the time next to the messages is correctly displayed.

### What Discord version do you have this issue on?

Stable, PTB
*(I haven't personally tested it on Canary, but I assume that the problem is also present(?))*

### Code of Conduct
```
- [X] I agree to follow this project's Code of Conduct

**Comment by TheCommieAxolotl** [comment]
Can you please test with the latest commit

**Comment by Lusiiky** [comment]
> Can you please test with the latest commit

Unfortunately that doesn't seem to work, Stable or PTB.
Re-enabling the plugin doesn't display the timezone on the user's profile, a restart of Discord is still required.

**Comment by Lusiiky** [comment]
@Lucatir
> I am using the plugin version 1.1.1 and I do not see the timezone in the user's profile in any situation (checked both the popup and full profile since I forgot which was supposed to show it), but as the original reporter posted, I can see it just fine in their messages.

Same for me now.

**Comment by zrodevkaan** [comment]
:)

**Comment by Lusiiky** [comment]
Hello,
In PTB at least, the timezoned time does appear in the general profile, but not in the small profile menu to the right of the messages with the person.

**Comment by pinetreemoonlight** [comment]
Timezones worked briefly with Timezones 1.1.2 update, but then Discord (main client) pushed out an update, and now timezones do not show again, neither in individual messages, nor in the DM's right-side panel.

**Comment by TheCommieAxolotl** [comment]
Please try again with v1.2.0, if still broken, I will reopen

**Comment by Lusiiky** [comment]
> Please try again with v1.2.0, if still broken, I will reopen

For my part, I'm not sure it works, on PTB.
![image](https://github.com/user-attachments/assets/3374705c-12ce-4692-b4ef-0bbcb0c19dea)

Thank you,
Lusiiky
