### ISSUE TITLE
[Bug] Endless update loop

### ISSUE THREAD

**Issue by TheByKotik** [TheCommieAxolotl/BetterDiscord-Stuff#88]
### Addon

Timezones

### What happened?

Endless update loop because:
https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/blob/9a0f8998e4e06751c080d86d3303199c4a780938/Timezones/Timezones.plugin.js#L5
https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/blob/9a0f8998e4e06751c080d86d3303199c4a780938/Timezones/Timezones.plugin.js#L24

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by master3395** [comment]
https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/pull/89
