### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by LilArylis** [TheCommieAxolotl/BetterDiscord-Stuff#98]
### Addon

Timezones Plugin for BetterDiscord

### What happened?

When I moved the folder into the plugins folder for BetterDiscord I got an error. and it wont let me use the plugin at all
![image_2024-07-25_130037176](https://github.com/user-attachments/assets/6895da2c-cfad-4b7e-900d-c8acb22beb09)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LilArylis** [comment]
I am not sure which version of discord I have. I just have it downloaded to my pc.

**Comment by TheCommieAxolotl** [comment]
Download the latest version from [the source](https://github.com/TheCommieAxolotl/BetterDiscord-Stuff/blob/main/Timezones/Timezones.plugin.js)
